# Generated by Django 5.2.4 on 2025-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
